# Generated by Django 4.2.30 on 2026-09-17 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=tracker.models.bug_number, editable=False, max_length=20, unique=True)),
                ('round', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200, verbose_name='Bug 标题')),
                ('steps', models.TextField(verbose_name='复现步骤')),
                ('actual', models.TextField(verbose_name='实际结果')),
                ('expected', models.TextField(verbose_name='期望结果')),
                ('environment', models.CharField(max_length=200, verbose_name='运行环境')),
                ('discovered_version', models.CharField(max_length=100, verbose_name='发现版本')),
                ('severity', models.CharField(choices=[('critical', '致命'), ('major', '严重'), ('normal', '一般'), ('minor', '轻微')], default='normal', max_length=10, verbose_name='严重程度')),
                ('priority', models.CharField(choices=[('P0', 'P0 · 紧急'), ('P1', 'P1 · 高'), ('P2', 'P2 · 中'), ('P3', 'P3 · 低')], default='P2', max_length=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('open', '待修复'), ('verify', '待回归'), ('closed', '已关闭')], default='open', max_length=10)),
                ('fix_version', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='当前负责人')),
            ],
            options={
                'verbose_name': 'Bug',
                'verbose_name_plural': 'Bug',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目说明')),
                ('archived', models.BooleanField(default=False, verbose_name='已归档')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=tracker.models.req_number, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('body', models.TextField(verbose_name='需求正文 / 验收标准')),
                ('priority', models.CharField(choices=[('P0', 'P0 · 紧急'), ('P1', 'P1 · 高'), ('P2', 'P2 · 中'), ('P3', 'P3 · 低')], default='P2', max_length=2, verbose_name='优先级')),
                ('stage', models.CharField(choices=[('0', '需求提出'), ('1', '需求规范整理'), ('2', '需求确认'), ('3', '分配开发'), ('4', '开发接单与实现'), ('5', '测试验收'), ('6', '需求方验收'), ('7', '代码上传'), ('8', '代码审核'), ('9', '结项检查'), ('10', '已完成')], default='0', max_length=2, verbose_name='当前环节')),
                ('round', models.PositiveIntegerField(default=1, verbose_name='处理轮次')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requirements', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requirements', to=settings.AUTH_USER_MODEL, verbose_name='当前负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='tracker.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('0', '需求提出'), ('1', '需求规范整理'), ('2', '需求确认'), ('3', '分配开发'), ('4', '开发接单与实现'), ('5', '测试验收'), ('6', '需求方验收'), ('7', '代码上传'), ('8', '代码审核'), ('9', '结项检查'), ('10', '已完成')], max_length=2)),
                ('round', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=30)),
                ('note', models.TextField()),
                ('commit', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('snapshot', models.JSONField(default=dict)),
                ('incomplete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='tracker.requirement')),
            ],
            options={
                'verbose_name': '流程记录',
                'verbose_name_plural': '流程记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('note', models.TextField()),
                ('commit', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='tracker.bug')),
                ('previous_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='tracker.requirement'),
        ),
        migrations.AddField(
            model_name='bug',
            name='test_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.record'),
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.project')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('0', '需求提出'), ('1', '需求规范整理'), ('2', '需求确认'), ('3', '分配开发'), ('4', '开发接单与实现'), ('5', '测试验收'), ('6', '需求方验收'), ('7', '代码上传'), ('8', '代码审核'), ('9', '结项检查'), ('10', '已完成')], max_length=2)),
                ('round', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bug_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='tracker.bugevent')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.record')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='tracker.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('需求提起人', '需求提起人'), ('产品负责人', '产品负责人'), ('分配负责人', '分配负责人'), ('开发人员', '开发人员'), ('测试负责人', '测试负责人'), ('代码审核人', '代码审核人'), ('结项人', '结项人')], max_length=30, verbose_name='角色')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tracker.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'unique_together': {('project', 'user', 'role')},
            },
        ),
    ]
