# Generated by Django 4.2.30 on 2026-09-23 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='接口名称')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.project')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('screenshot', '群聊截图'), ('document', '文档附件')], default='document', max_length=20),
        ),
        migrations.AddField(
            model_name='attachment',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bug',
            name='business_owner',
            field=models.CharField(blank=True, max_length=120, verbose_name='开发负责人'),
        ),
        migrations.AddField(
            model_name='bug',
            name='discovery_stage',
            field=models.CharField(choices=[('0', '需求提出'), ('1', '需求规范整理'), ('2', '需求确认'), ('3', '分配开发'), ('4', '开发接单与实现'), ('5', '测试验收'), ('6', '需求方验收'), ('7', '代码上传'), ('8', '代码审核'), ('9', '结项检查'), ('10', '已完成')], default='5', max_length=2, verbose_name='发现环节'),
        ),
        migrations.AddField(
            model_name='bugevent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='record',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='业务发生时间'),
        ),
        migrations.AddField(
            model_name='record',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='requirement',
            name='business_owner',
            field=models.CharField(blank=True, max_length=120, verbose_name='当前业务负责人'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='proposer',
            field=models.CharField(blank=True, max_length=120, verbose_name='需求提起人'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_group',
            field=models.CharField(blank=True, max_length=200, verbose_name='来源群组 / 标识'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='version',
            field=models.CharField(blank=True, max_length=100, verbose_name='需求版本'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='原账号负责人'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='test_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.record'),
        ),
        migrations.AlterField(
            model_name='bugevent',
            name='previous_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugevent',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('需求提起人', '需求提起人'), ('产品负责人', '产品负责人'), ('分配负责人', '分配负责人'), ('开发人员', '开发人员'), ('测试负责人', '测试负责人'), ('代码审核人', '代码审核人'), ('结项人', '结项人'), ('记录人员', '记录人员')], max_length=30, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='record',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requirements', to=settings.AUTH_USER_MODEL, verbose_name='原账号负责人'),
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(max_length=64)),
                ('count', models.PositiveIntegerField(default=0)),
                ('conflicts', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.dataconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问题标题')),
                ('version', models.CharField(max_length=100, verbose_name='对应版本')),
                ('provider', models.CharField(max_length=120, verbose_name='意见提供人')),
                ('category', models.CharField(choices=[('frontend', '前端审查'), ('backend', '后端审查'), ('test', '测试复查')], max_length=20, verbose_name='审查类别')),
                ('risk', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='建议风险等级')),
                ('description', models.TextField(verbose_name='现象、证据与优化建议')),
                ('reproduction', models.TextField(blank=True, verbose_name='人工复现资料 / 说明')),
                ('status', models.CharField(choices=[('pending', '待决策'), ('working', '处理中'), ('done', '已处理'), ('deferred', '暂缓')], default='pending', max_length=20, verbose_name='线下处理情况')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('snapshot', models.JSONField(default=dict)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.project')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='统计日期')),
                ('channel', models.CharField(max_length=100, verbose_name='渠道')),
                ('provider', models.CharField(max_length=120, verbose_name='资料提供人')),
                ('visits', models.PositiveIntegerField(blank=True, null=True, verbose_name='访问次数（不详留空）')),
                ('registrations', models.PositiveIntegerField(blank=True, null=True, verbose_name='注册数（不详留空）')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='推广费用 USD')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='收入 USD（未归因）')),
                ('source', models.TextField(verbose_name='来源文件 / 说明')),
                ('source_type', models.CharField(choices=[('manual', '人工录入'), ('api', '接口同步')], default='manual', max_length=10)),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待核对'), ('verified', '已核对'), ('conflict', '待处理差异')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.project')),
            ],
            options={
                'ordering': ['-day', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('0', '需求提出'), ('1', '需求规范整理'), ('2', '需求确认'), ('3', '分配开发'), ('4', '开发接单与实现'), ('5', '测试验收'), ('6', '需求方验收'), ('7', '代码上传'), ('8', '代码审核'), ('9', '结项检查')], max_length=2, verbose_name='确认环节')),
                ('round', models.PositiveIntegerField(default=1)),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='对应版本')),
                ('confirmer', models.CharField(blank=True, max_length=120, verbose_name='群组确认人')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='群组确认时间')),
                ('conclusion', models.CharField(choices=[('pending', '待明确'), ('confirmed', '明确通过'), ('rejected', '未通过')], default='pending', max_length=20, verbose_name='聊天确认结论')),
                ('summary', models.TextField(blank=True, verbose_name='确认原意摘要')),
                ('checked', models.BooleanField(default=False, verbose_name='已核对截图中的确认人、版本和明确意见')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='tracker.requirement')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='资产名称')),
                ('kind', models.CharField(choices=[('domain', '域名'), ('server', '服务器'), ('account', '平台账号')], max_length=20, verbose_name='类型')),
                ('identifier', models.CharField(blank=True, max_length=200, verbose_name='资源 / 账号标识')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应商 / 所属账号')),
                ('business_owner', models.CharField(max_length=120, verbose_name='业务负责人')),
                ('expires_on', models.DateField(verbose_name='到期日')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='费用 USD')),
                ('purpose', models.TextField(verbose_name='用途')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.project')),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='波动标题')),
                ('metric', models.CharField(max_length=100, verbose_name='统计指标及单位')),
                ('before_at', models.DateTimeField(blank=True, null=True, verbose_name='前时点（可留空）')),
                ('after_at', models.DateTimeField(blank=True, null=True, verbose_name='后时点（可留空）')),
                ('before_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='前时点数值')),
                ('after_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='后时点数值')),
                ('provider', models.CharField(max_length=120, verbose_name='资料提供人')),
                ('source', models.TextField(verbose_name='数据来源 / 材料说明')),
                ('description', models.TextField(verbose_name='初步现象与待核查事项')),
                ('status', models.CharField(choices=[('pending', '待核查'), ('working', '核查中'), ('done', '已留存结论')], default='pending', max_length=20, verbose_name='核查状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.project')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='tracker.confirmation'),
        ),
        migrations.AddConstraint(
            model_name='syncrun',
            constraint=models.UniqueConstraint(fields=('connection', 'request_id'), name='unique_sync_request'),
        ),
        migrations.AddConstraint(
            model_name='dailydata',
            constraint=models.UniqueConstraint(fields=('project', 'day', 'channel'), name='unique_project_channel_day'),
        ),
    ]
